<?php

namespace Proxies\__CG__\AERGUS\associationBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Bureau extends \AERGUS\associationBundle\Entity\Bureau implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'nom', 'programme', 'membres', 'sorties', 'entrees', 'reunions', '' . "\0" . 'AERGUS\\associationBundle\\Entity\\Bureau' . "\0" . 'projets');
        }

        return array('__isInitialized__', 'id', 'nom', 'programme', 'membres', 'sorties', 'entrees', 'reunions', '' . "\0" . 'AERGUS\\associationBundle\\Entity\\Bureau' . "\0" . 'projets');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Bureau $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setProgramme(\AERGUS\associationBundle\Entity\Programme $programme = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProgramme', array($programme));

        return parent::setProgramme($programme);
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramme', array());

        return parent::getProgramme();
    }

    /**
     * {@inheritDoc}
     */
    public function addMembre(\AERGUS\associationBundle\Entity\Membre $membre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMembre', array($membre));

        return parent::addMembre($membre);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMembre(\AERGUS\associationBundle\Entity\Membre $membre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMembre', array($membre));

        return parent::removeMembre($membre);
    }

    /**
     * {@inheritDoc}
     */
    public function getMembres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMembres', array());

        return parent::getMembres();
    }

    /**
     * {@inheritDoc}
     */
    public function addSorty(\AERGUS\associationBundle\Entity\Sortant $sorty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSorty', array($sorty));

        return parent::addSorty($sorty);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSorty(\AERGUS\associationBundle\Entity\Sortant $sorty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSorty', array($sorty));

        return parent::removeSorty($sorty);
    }

    /**
     * {@inheritDoc}
     */
    public function getSorties()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSorties', array());

        return parent::getSorties();
    }

    /**
     * {@inheritDoc}
     */
    public function addEntree(\AERGUS\associationBundle\Entity\Entrant $entree)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEntree', array($entree));

        return parent::addEntree($entree);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEntree(\AERGUS\associationBundle\Entity\Entrant $entree)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEntree', array($entree));

        return parent::removeEntree($entree);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntrees()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntrees', array());

        return parent::getEntrees();
    }

    /**
     * {@inheritDoc}
     */
    public function addReunion(\AERGUS\associationBundle\Entity\Reunion $reunion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReunion', array($reunion));

        return parent::addReunion($reunion);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReunion(\AERGUS\associationBundle\Entity\Reunion $reunion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReunion', array($reunion));

        return parent::removeReunion($reunion);
    }

    /**
     * {@inheritDoc}
     */
    public function getReunions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReunions', array());

        return parent::getReunions();
    }

    /**
     * {@inheritDoc}
     */
    public function addProjet(\AERGUS\associationBundle\Entity\Projet $projet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProjet', array($projet));

        return parent::addProjet($projet);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProjet(\AERGUS\associationBundle\Entity\Projet $projet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProjet', array($projet));

        return parent::removeProjet($projet);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjets', array());

        return parent::getProjets();
    }

}
