<?php

namespace Proxies\__CG__\AERGUS\associationBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ressortissants extends \AERGUS\associationBundle\Entity\Ressortissants implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'nom', 'prenom', 'numeroDeTelephone', 'dateDeNaissance', 'anneeVenu', 'etat', 'section', 'membres');
        }

        return array('__isInitialized__', 'id', 'nom', 'prenom', 'numeroDeTelephone', 'dateDeNaissance', 'anneeVenu', 'etat', 'section', 'membres');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ressortissants $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroDeTelephone($numeroDeTelephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroDeTelephone', array($numeroDeTelephone));

        return parent::setNumeroDeTelephone($numeroDeTelephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroDeTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroDeTelephone', array());

        return parent::getNumeroDeTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDeNaissance($dateDeNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDeNaissance', array($dateDeNaissance));

        return parent::setDateDeNaissance($dateDeNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDeNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDeNaissance', array());

        return parent::getDateDeNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnneeVenu($anneeVenu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnneeVenu', array($anneeVenu));

        return parent::setAnneeVenu($anneeVenu);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnneeVenu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnneeVenu', array());

        return parent::getAnneeVenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setSection(\AERGUS\associationBundle\Entity\Section $section = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSection', array($section));

        return parent::setSection($section);
    }

    /**
     * {@inheritDoc}
     */
    public function getSection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSection', array());

        return parent::getSection();
    }

    /**
     * {@inheritDoc}
     */
    public function addMembre(\AERGUS\associationBundle\Entity\Membre $membre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMembre', array($membre));

        return parent::addMembre($membre);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMembre(\AERGUS\associationBundle\Entity\Membre $membre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMembre', array($membre));

        return parent::removeMembre($membre);
    }

    /**
     * {@inheritDoc}
     */
    public function getMembres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMembres', array());

        return parent::getMembres();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', array($etat));

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', array());

        return parent::getEtat();
    }

}
